```yaml
name: gallery
description: "A beautiful iOS Liquid Glass Launcher built on Flutter."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  installed_apps: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

```
